# Generated by Django 6.0.3 on 2026-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_drawing_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
